v0.5 | Update src/genpasswd, src/getip, src/manuser, src/unextract files and create install.sh script

diff --git a/src/manuser b/src/manuser
--- a/src/manuser
+++ b/src/manuser
@@ -1,5 +1,10 @@
 #!/usr/bin/env bash
 
+error() {
+  echo "$1"
+  exit 1
+}
+
 if [[ -z "$1" ]]; then
   read -p "Username: " username
 else
@@ -7,13 +12,11 @@ else
 fi
 
 if ! [[ -z "$USERNAME" ]]; then
-    echo "Enter a username please."
-    exit 1
+    error "Enter a username please."
 fi
 
 if ! id "$username" >/dev/null 2>&1; then
-  echo "User not found. Please create user first."
-  exit 1
+  error "User not found. Please create user first."
 fi
 
 clear
@@ -58,7 +61,6 @@ case $choice in
     exit 0
     ;;
   *)
-    echo "Invalid choice."
-    exit 1
+    error "Invalid choice."
     ;;
 esac
